[package]
name = "day-6-wtf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoclib = { path = "../aoclib" }
bitvec = "0.22.3"
indicatif = "0.16.2"
rayon = "1.5.1"
